version: 2

models:
  - name: fct_daily_events
    description: "Daily aggregated event metrics for analytics dashboard"
    columns:
      - name: event_date_raw
        description: "Date in YYYYMMDD format"
        tests:
          - unique
          - not_null
      - name: event_count
        description: "Total events on this date"
        tests:
          - not_null

  - name: dim_actors
    description: "Actor dimension with aggregated statistics"
    columns:
      - name: actor_name
        description: "Name of the actor"
        tests:
          - unique
          - not_null
      - name: total_events
        description: "Total events involving this actor"
        tests:
          - not_null

  - name: dim_countries
    description: "Country dimension with aggregated event statistics"
    columns:
      - name: country_code
        description: "3-letter ISO country code"
        tests:
          - unique
          - not_null
      - name: total_events
        description: "Total events from this country"
        tests:
          - not_null
