[server]
maxUploadSize = 50
enableCORS = false
enableXsrfProtection = true
fileWatcherType = "poll"

[runner]
magicEnabled = false
fastReruns = true

[client]
showErrorDetails = true

[logger]
level = "info"
